# Generated by Django 4.2.26 on 2025-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_budget_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when budget thresholds are reached",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(
                default=True, help_text="Receive email notifications for budget alerts"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_recurring_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Receive email reminders for upcoming recurring transactions",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_weekly_summary",
            field=models.BooleanField(
                default=False, help_text="Receive weekly financial summary emails"
            ),
        ),
    ]
