# Generated by Django 4.2.26 on 2025-12-28 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, help_text='Ticker symbol if applicable', max_length=20)),
                ('investment_type', models.CharField(choices=[('STOCK', 'Stock/Shares'), ('BOND', 'Bond'), ('MMF', 'Money Market Fund'), ('MUTUAL_FUND', 'Mutual Fund'), ('ETF', 'ETF'), ('TREASURY_BILL', 'Treasury Bill'), ('TREASURY_BOND', 'Treasury Bond'), ('SACCO_SHARES', 'SACCO Shares'), ('UNIT_TRUST', 'Unit Trust'), ('REAL_ESTATE', 'Real Estate/REIT'), ('CRYPTO', 'Cryptocurrency'), ('PENSION', 'Pension/Retirement'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price per unit at purchase', max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('purchase_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current price per unit', max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest/dividend rate as percentage', max_digits=5)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, help_text='e.g., NSE, CIC, Britam, Binance', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('MATURED', 'Matured')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('BONUS', 'Bonus Shares'), ('SPLIT', 'Stock Split'), ('FEE', 'Fee/Charge')], max_length=10)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
