# Generated by Django 4.2.26 on 2025-12-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('STOCK', 'Stock/Shares'), ('BOND', 'Bond'), ('MMF', 'Money Market Fund'), ('MUTUAL_FUND', 'Mutual Fund'), ('ETF', 'ETF'), ('TREASURY_BILL', 'Treasury Bill'), ('TREASURY_BOND', 'Treasury Bond'), ('SACCO_SHARES', 'SACCO Shares'), ('UNIT_TRUST', 'Unit Trust'), ('REAL_ESTATE', 'Real Estate/REIT'), ('CRYPTO', 'Cryptocurrency'), ('PENSION', 'Pension/Retirement'), ('INSURANCE_ENDOWMENT', 'Insurance - Endowment'), ('INSURANCE_WHOLE_LIFE', 'Insurance - Whole Life'), ('INSURANCE_EDUCATION', 'Insurance - Education Plan'), ('INSURANCE_INVESTMENT', 'Insurance - Investment Linked'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
