# Generated by Django 4.2.26 on 2025-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_add_insurance_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="bond_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INFRASTRUCTURE", "Infrastructure Bond (Tax-Free)"),
                    ("CORPORATE", "Corporate Bond"),
                    ("GOVERNMENT", "Government Bond"),
                    ("MUNICIPAL", "Municipal Bond"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="dividend_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Annual dividend rate on deposits",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="face_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Par/Face value for bonds",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="loan_interest_rebate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Interest rebate rate on loans",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="monthly_costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly costs (maintenance, management, insurance, etc.)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="monthly_rent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly rental income",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="next_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="occupancy_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("OCCUPIED", "Occupied"),
                    ("VACANT", "Vacant"),
                    ("PARTIALLY", "Partially Occupied"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("SEMI_ANNUAL", "Semi-Annual"),
                    ("ANNUAL", "Annual"),
                    ("AT_MATURITY", "At Maturity"),
                ],
                default="NONE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="premium_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Premium amount per payment",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="premium_frequency",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("SEMI_ANNUAL", "Semi-Annual"),
                    ("ANNUAL", "Annual"),
                    ("AT_MATURITY", "At Maturity"),
                ],
                default="NONE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="property_tax_annual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Annual property tax/rates",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="sum_assured",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Death benefit / Maturity value",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="surrender_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current surrender/cash value",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Withholding tax rate on interest (0 for infra bonds, 15 for others)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Current price per unit or current value",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Annual interest/coupon/dividend rate as percentage",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="investment_type",
            field=models.CharField(
                choices=[
                    ("STOCK", "Stock/Shares"),
                    ("BOND", "Bond"),
                    ("MMF", "Money Market Fund"),
                    ("MUTUAL_FUND", "Mutual Fund"),
                    ("ETF", "ETF"),
                    ("TBILL", "Treasury Bill"),
                    ("TBOND", "Treasury Bond"),
                    ("FIXED_DEPOSIT", "Fixed Deposit"),
                    ("SACCO", "SACCO"),
                    ("UNIT_TRUST", "Unit Trust"),
                    ("REAL_ESTATE", "Real Estate"),
                    ("CRYPTO", "Cryptocurrency"),
                    ("PENSION", "Pension/Retirement"),
                    ("INSURANCE_ENDOWMENT", "Insurance - Endowment"),
                    ("INSURANCE_WHOLE_LIFE", "Insurance - Whole Life"),
                    ("INSURANCE_EDUCATION", "Insurance - Education Plan"),
                    ("INSURANCE_INVESTMENT", "Insurance - Investment Linked"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price per unit or total amount",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Units, shares, or face value",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text="Ticker symbol, policy number, or reference",
                max_length=50,
            ),
        ),
    ]
