# Generated by Codex on 2025-02-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_add_detailed_investment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='investment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='investment_transactions',
                to='investments.investment',
            ),
        ),
    ]
