# Generated by Django 4.2.26 on 2025-11-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_savings_goal'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcontribution',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_contribution', to='finance.transaction'),
        ),
    ]
