# Generated by Django 4.2.26 on 2025-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_goalcontribution_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate as a percentage (e.g., 10 for 10%)', max_digits=5),
        ),
    ]
