# Generated by Django 4.2.26 on 2025-11-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('finance', '0002_recurringtransaction_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='savings.savingsgoal'),
        ),
    ]
