# Generated by Django 4.2.26 on 2026-01-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_add_double_entry"),
        ("finance", "0003_transaction_savings_goal"),
    ]

    operations = []
