# Generated by Django 4.2.26 on 2026-01-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_add_sms_tracking_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="finance_tra_source_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="finance_tra_sms_ref_idx",
        ),
    ]
