# Generated by Django 4.2.26 on 2025-11-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('liability_type', models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('LOAN', 'Loan'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], default='LOAN', max_length=20)),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in %', max_digits=5)),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('MMF', 'Money Market Fund'), ('STOCK', 'Stock'), ('BOND', 'Bond'), ('LAND', 'Land'), ('VEHICLE', 'Vehicle'), ('BUSINESS', 'Business'), ('PENSION', 'Pension'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=16)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
