# Generated by Django 4.2.26 on 2025-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when the loan started', null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='tenure_months',
            field=models.PositiveIntegerField(blank=True, help_text='Total loan tenure in months', null=True),
        ),
    ]
