# Generated by Django 4.2.26 on 2025-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0002_add_tenure_to_liability'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of source record (Investment or Account)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('ACCOUNT', 'From Account'), ('INVESTMENT', 'From Investment')], default='MANUAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('user', 'source_type', 'source_id'), name='unique_asset_source'),
        ),
    ]
