# Generated by Django 4.2.26 on 2025-12-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0003_add_source_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('MMF', 'Money Market Fund'), ('STOCK', 'Stock'), ('BOND', 'Bond'), ('LAND', 'Land'), ('VEHICLE', 'Vehicle'), ('BUSINESS', 'Business'), ('PENSION', 'Pension'), ('INSURANCE', 'Insurance (Cash Value)'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
