# Generated by hand
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                (
                    'level',
                    models.CharField(
                        choices=[
                            ('INFO', 'Info'),
                            ('SUCCESS', 'Success'),
                            ('WARNING', 'Warning'),
                            ('ERROR', 'Error'),
                        ],
                        default='INFO',
                        max_length=10,
                    ),
                ),
                ('is_read', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('email_sent', models.BooleanField(default=False)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
